### ISSUE TITLE
Render to Bitmap

### ISSUE THREAD

**Issue by lostmsu** [AvaloniaUI/Avalonia.HtmlRenderer#10]
Is it possible to render content to Avalonia `Bitmap`? Original project has a `HtmlRender.RenderToImage` that fulfills this purpose.

**Comment by kekekeks** [comment]
Here is an example to rendering any control to a bitmap:
```cs
void RenderToFile(Control target, string path)
{
    var pixelSize = new PixelSize((int) target.Width, (int) target.Height);
    var size = new Size(target.Width, target.Height);
    using (RenderTargetBitmap bitmap = new RenderTargetBitmap(pixelSize, new Vector(96, 96)))
    {
        target.Measure(size);
        target.Arrange(new Rect(size));
        bitmap.Render(target);
        bitmap.Save(path);
    }
}
```

I guess with `HtmlRenderer` you need to tinker with dimensions and `Measure`

**Comment by lostmsu** [comment]
It feels wrong to create controls just to render an image. Is there no more direct way? The library appears to have its own layout engine.

**Comment by kekekeks** [comment]
The original project also creates a control (DrawingVisual): https://github.com/ArthurHub/HTML-Renderer/blob/a004aefeb87b5226aece75c49e84040dbaf9f3e0/Source/HtmlRenderer.WPF/HtmlRender.cs#L221-L236

**Comment by maxkatz6** [comment]
HtmlRender ported (you need non-transparent background to avoid some rendering issues...)
