### ISSUE TITLE
Update used Avalonia version / update nuget package

### ISSUE THREAD

**Issue by FRvanderVeen** [AvaloniaUI/Avalonia.HtmlRenderer#13]
Is it possible to update the used Avalonia version in this project? I was using the nuget package of this project (version 0.6.1), in conjunction with NetSparkle.
When trying to open an update window from the netsparkle library the following error is thrown:
![image](https://user-images.githubusercontent.com/86024496/152872500-a0e38df6-578b-44a3-9a5a-7bddefd8c03c.png)
When I download the source code of this project and remove the nuget package reference and change it to a project reference, everything is working fine.
For now I can workaround by using the source code of this repository, but a refreshed nuget package would come in handy.

**Comment by maxkatz6** [comment]
Updated nuget package
