### ISSUE TITLE
Avalonia.Browser demo broken?

### ISSUE THREAD

**Issue by midget35** [AvaloniaUI/Avalonia.HtmlRenderer#26]
Hi there,

The Html renderer looks great. Really impressed running the demo desktop app.

Unfortunately - I cannot get passed the below error with the Browser app. Tried multiple browsers running on Windows 10.

Uncaught SyntaxError SyntaxError: The requested module './avalonia.js' does not provide an export named 'registerAvaloniaModule'
    at (program) (localhost꞉5001/main.js:2:10)  

Thanks for any help!

**Comment by maxkatz6** [comment]
fixed

**Comment by midget35** [comment]
> fixed [ceafaa1](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/commit/ceafaa167f0c1287733d9430c2d91382dd5757b2)

It is fixed! Fantastic! Thank you so much!
