### ISSUE TITLE
HtmlLabel and HtmlPanel are not available on v0.10

### ISSUE THREAD

**Issue by cotti** [AvaloniaUI/Avalonia.HtmlRenderer#27]
Hello. I can't seem to be able to use both HtmlLabel and HtmlPanel on v0.10. I have tested v11 and it worked fine.

When I declare a XAML namespace for the HtmlRenderer package, only HtmlContainer is shown.

Creating a fresh project, adding the 0.10 nuget package, adding the namespace and trying to find the controls result in the following:

![image](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/assets/889227/d426083b-0d8d-4a02-9baf-ac367460587b)

https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/assets/889227/e5f8b256-81be-4a77-8a93-8bff4cda63d2

The code-behind also doesn't feature them:

![image](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/assets/889227/4002fcea-01ee-49b9-97ef-eaf5b45a56b7)

And these are the contents of the namespace in v11, which is the expected:

![image](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/assets/889227/6fdd1eaf-2e4d-48cc-890b-e72cbabf821b)

**Comment by Gillibald** [comment]
HtmlRenderer v. [0.10.0] will not get any updates. For the latest features and fixes you need to upgrade to Avalonia 11

**Comment by maxkatz6** [comment]
In 0.10 you can use HtmlContainer inside of ScrollPanel, if you need scrolling. Other than that, HtmlPanel isn't much different.
