### ISSUE TITLE
No scrolling in stack panel

### ISSUE THREAD

**Issue by CoolCoderSuper** [AvaloniaUI/Avalonia.HtmlRenderer#28]
When you place the render in a stack panel the scroll bar disappears.

**Comment by maxkatz6** [comment]
It is expected. You can't vertically scroll in a StackPanel, as StackPanel doesn't vertically restrict your content. 
In other words, scroll gets infinite height, meaning it doesn't need to scroll anything. 

Use other kinds of panels like DockPanel or Grid here.
