### ISSUE TITLE
.css class "Display: flex;" dose not render when applyed

### ISSUE THREAD

**Issue by MercyPillow** [AvaloniaUI/Avalonia.HtmlRenderer#30]
Css in the style div on the head does not respect the display flag flex, and renders nothing with the class applyed.

<head>
    <style>
      .banner {
	      width: 100%;
	      height: auto;
	      position: relative;
	      justify-content: center;
	      align-items: center;
	      display: flex;
      }
  </style>
</head>

**Comment by kekekeks** [comment]
display: flex is not a part of HTML 4.01 / CSS 2  specs
